// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 
//      Major Version
//      Minor Version
//      Build Number
//      Revision

using System.Reflection;

[assembly: AssemblyVersion("1.0.2061.304")]
[assembly: AssemblyFileVersion("1.0.2061.304")]
